### ISSUE TITLE
unset keybind display none

### ISSUE THREAD

**Issue by jeff8912** [atom/solarized-light-syntax#33]
![image](https://cloud.githubusercontent.com/assets/16128904/23455052/510b0c16-fea9-11e6-907b-126d0256155a.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
